import type { AnalysisResult } from "./types";

export function buildPlaintextSummary(r: AnalysisResult): string {
  const lines: string[] = [];
  lines.push("Permitted MCP analysis");
  lines.push("======================");
  lines.push(`Servers: ${r.totalServers}`);
  lines.push(`Permission surface: ${r.categories.length ? r.categories.join(", ") : "none"}`);
  if (r.highestRisk) lines.push(`Highest risk: ${r.highestRisk}`);
  lines.push("");
  for (const s of r.servers) {
    lines.push(`- ${s.name}`);
    if (s.pkg) lines.push(`    package: ${s.pkg}`);
    else if (s.command) lines.push(`    command: ${s.command}${s.args.length ? " " + s.args.slice(0, 3).join(" ") : ""}`);
    lines.push(`    categories: ${s.categories.join(", ")}`);
    if (s.envKeys.length) lines.push(`    env keys: ${s.envKeys.join(", ")}`);
  }
  lines.push("");
  lines.push("Generated by permitted.io/mcp. Parsing runs in your browser.");
  return lines.join("\n");
}
